# Generated by Django 5.1.7 on 2025-11-02 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("farm_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ndvi_value", models.FloatField()),
                ("soil_ph", models.FloatField()),
                ("nitrogen_percent", models.FloatField(default=0.0)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farm_management.farmfield",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeatherRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("rainfall_mm", models.FloatField()),
                ("max_temp", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farm_management.farmfield",
                    ),
                ),
            ],
        ),
    ]
